spring:
  application:
    name: meliapp-registry
server:
  port: 8099
eureka:
  instance:
    hostname: meliapp-registry.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: https://meliapp-registry.herokuapp.com/eureka/